ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 0  
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 1
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 2
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 3
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 4
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 5
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 6
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 7
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 8
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 9
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 10
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 11
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 12
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 13
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 14
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 15
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 16
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 17
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 18
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 19
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 20
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 21
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 22
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 23
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 24
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 25
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 26
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag2p-ht500 --plot_directory training_2p --noData --mva 27

ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 0  
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 1
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 2
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 3
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 4
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 5
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 6
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 7
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 8
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 9
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 10
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 11
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 12
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 13
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 14
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 15
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 16
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 17
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 18
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 19
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 20
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 21
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 22
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 23
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 24
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 25
ipython3 analysis-2l_only_mva2p.py -- --selection dilepL-offZ1-njet4p-btag3p-ht500 --plot_directory training_3p --noData --mva 26
