python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_hdamp --sample TTLep_hUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_hdamp --sample TTLep_hDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_hdamp --sample TTLep

#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_nominal
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesTotalUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesAbsoluteMPFBiasUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesAbsoluteScaleUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesAbsoluteStatUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeBalUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeFSRUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeJEREC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeJEREC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeJERHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativePtBBUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativePtEC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativePtEC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativePtHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeStatECUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeStatFSRUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeStatHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpDataMCUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpPtBBUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpPtEC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpPtEC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpPtHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpPtRefUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesFlavorQCDUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesFragmentationUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesSinglePionECALUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesSinglePionHCALUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesTimePtEtaUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesTotalDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesAbsoluteMPFBiasDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesAbsoluteScaleDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesAbsoluteStatDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeBalDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeFSRDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeJEREC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeJEREC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeJERHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativePtBBDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativePtEC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativePtEC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativePtHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeStatECDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeStatFSRDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesRelativeStatHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpDataMCDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpPtBBDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpPtEC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpPtEC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpPtHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesPileUpPtRefDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesFlavorQCDDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesFragmentationDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesSinglePionECALDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesSinglePionHCALDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_0p5_jesTimePtEtaDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesTotalUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesAbsoluteMPFBiasUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesAbsoluteScaleUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesAbsoluteStatUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeBalUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeFSRUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeJEREC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeJEREC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeJERHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativePtBBUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativePtEC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativePtEC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativePtHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeStatECUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeStatFSRUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeStatHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpDataMCUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpPtBBUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpPtEC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpPtEC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpPtHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpPtRefUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesFlavorQCDUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesFragmentationUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesSinglePionECALUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesSinglePionHCALUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesTimePtEtaUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesTotalDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesAbsoluteMPFBiasDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesAbsoluteScaleDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesAbsoluteStatDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeBalDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeFSRDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeJEREC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeJEREC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeJERHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativePtBBDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativePtEC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativePtEC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativePtHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeStatECDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeStatFSRDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesRelativeStatHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpDataMCDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpPtBBDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpPtEC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpPtEC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpPtHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesPileUpPtRefDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesFlavorQCDDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesFragmentationDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesSinglePionECALDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesSinglePionHCALDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p0_jesTimePtEtaDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesTotalUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesAbsoluteMPFBiasUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesAbsoluteScaleUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesAbsoluteStatUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeBalUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeFSRUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeJEREC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeJEREC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeJERHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativePtBBUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativePtEC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativePtEC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativePtHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeStatECUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeStatFSRUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeStatHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpDataMCUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpPtBBUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpPtEC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpPtEC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpPtHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpPtRefUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesFlavorQCDUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesFragmentationUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesSinglePionECALUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesSinglePionHCALUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesTimePtEtaUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesTotalDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesAbsoluteMPFBiasDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesAbsoluteScaleDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesAbsoluteStatDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeBalDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeFSRDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeJEREC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeJEREC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeJERHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativePtBBDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativePtEC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativePtEC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativePtHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeStatECDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeStatFSRDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesRelativeStatHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpDataMCDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpPtBBDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpPtEC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpPtEC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpPtHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesPileUpPtRefDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesFlavorQCDDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesFragmentationDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesSinglePionECALDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesSinglePionHCALDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_1p5_jesTimePtEtaDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesTotalUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesAbsoluteMPFBiasUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesAbsoluteScaleUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesAbsoluteStatUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeBalUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeFSRUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeJEREC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeJEREC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeJERHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativePtBBUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativePtEC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativePtEC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativePtHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeStatECUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeStatFSRUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeStatHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpDataMCUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpPtBBUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpPtEC1Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpPtEC2Up
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpPtHFUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpPtRefUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesFlavorQCDUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesFragmentationUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesSinglePionECALUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesSinglePionHCALUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesTimePtEtaUp
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesTotalDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesAbsoluteMPFBiasDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesAbsoluteScaleDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesAbsoluteStatDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeBalDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeFSRDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeJEREC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeJEREC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeJERHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativePtBBDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativePtEC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativePtEC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativePtHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeStatECDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeStatFSRDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesRelativeStatHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpDataMCDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpPtBBDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpPtEC1Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpPtEC2Down
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpPtHFDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesPileUpPtRefDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesFlavorQCDDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesFragmentationDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesSinglePionECALDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesSinglePionHCALDown
#python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/tt-jec/training-ntuples-3 --config tt_jec --sample TTLep_2p0_jesTimePtEtaDown 
