python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys LeptonSFDown 
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys LeptonSFUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys PUDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys PUUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys L1PrefireDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys L1PrefireUp
#python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys TriggerDown
#python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys TriggerUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFJesDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFJesUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFHfDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFHfUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFLfDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFLfUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFHfs1Down
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFHfs1Up
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFLfs1Down
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFLfs1Up
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFHfs2Down
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFHfs2Up
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFLfs2Down
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFLfs2Up
#python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFCfe1Down
#python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFCfe1Up
#python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFCfe2Down
#python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys BTagSFCfe2Up
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesTotalUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesTotalDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesAbsoluteMPFBiasUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesAbsoluteMPFBiasDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesAbsoluteScaleUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesAbsoluteScaleDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesAbsoluteStatUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesAbsoluteStatDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeBalUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeBalDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeFSRUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeFSRDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeJEREC1Up
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeJEREC1Down
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeJEREC2Up
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeJEREC2Down
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeJERHFUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeJERHFDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativePtBBUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativePtBBDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativePtEC1Up
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativePtEC1Down
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativePtEC2Up
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativePtEC2Down
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativePtHFUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativePtHFDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeStatECUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeStatECDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeStatFSRUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeStatFSRDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeStatHFUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesRelativeStatHFDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpDataMCUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpDataMCDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpPtBBUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpPtBBDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpPtEC1Up
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpPtEC1Down
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpPtEC2Up
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpPtEC2Down
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpPtHFUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpPtHFDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpPtRefUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesPileUpPtRefDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesFlavorQCDUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesFlavorQCDDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesFragmentationUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesFragmentationDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesSinglePionECALUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesSinglePionECALDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesSinglePionHCALUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesSinglePionHCALDown
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesTimePtEtaUp
python analysis-2l-systematics.py --plot_directory 4t_syst_v2 --selection trg-dilepL-minDLmass20-offZ1-njet4p-btag3p-ht500 --sys jesTimePtEtaDown
