##python aggregateSystematics.py --plot_directory 4t-v17-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet6p-btag3p-ht500 --out_directory 4t-v20-syst
##python aggregateSystematics.py --plot_directory 4t-v17-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet6p-btag2-ht500 --out_directory 4t-v20-syst
##python aggregateSystematics.py --plot_directory 4t-v17-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet6p-btag1-ht500 --out_directory 4t-v20-syst
#python aggregateSystematics.py --plot_directory 4t-v15-syst_mvaCut0.2p --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4to5-btag3p-ht500 --out_directory 4t-v21-syst
#python aggregateSystematics.py --plot_directory 4t-v15-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4to5-btag2-ht500 --out_directory 4t-v21-syst
#python aggregateSystematics.py --plot_directory 4t-v15-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4to5-btag1-ht500 --out_directory 4t-v21-syst
#python aggregateSystematics.py --plot_directory 4t-v15-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet6to7-btag3p-ht500 --out_directory 4t-v21-syst
#python aggregateSystematics.py --plot_directory 4t-v15-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet6to7-btag2-ht500 --out_directory 4t-v21-syst
#python aggregateSystematics.py --plot_directory 4t-v15-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet6to7-btag1-ht500 --out_directory 4t-v21-syst
#python aggregateSystematics.py --plot_directory 4t-v15-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet8p-btag3p-ht500 --out_directory 4t-v21-syst
#python aggregateSystematics.py --plot_directory 4t-v15-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet8p-btag2-ht500 --out_directory 4t-v21-syst
#python aggregateSystematics.py --plot_directory 4t-v15-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet8p-btag1-ht500 --out_directory 4t-v21-syst
##python aggregateSystematics.py --plot_directory 4t-v15-syst_mvaCut0.1m --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet6to7-btag3p-ht500 --out_directory 4t-v15-syst
##python aggregateSystematics.py --plot_directory 4t-v15-syst_mvaCut0.1p --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet6to7-btag3p-ht500 --out_directory 4t-v15-syst
##python aggregateSystematics.py --plot_directory 4t-v15-syst_mvaCut0.2m --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4to5-btag3p-ht500 --out_directory 4t-v15-syst
##python aggregateSystematics.py --plot_directory 4t-v15-syst_mvaCut0.2p --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4to5-btag3p-ht500 --out_directory 4t-v15-syst
python aggregateSystematics.py --plot_directory 4t-v12-syst_mvaCut0.2p --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4to5-btag3p-ht500 --out_directory 4t-v20-syst
python aggregateSystematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4to5-btag2-ht500 --out_directory 4t-v20-syst
python aggregateSystematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4to5-btag1-ht500 --out_directory 4t-v20-syst
python aggregateSystematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet6to7-btag3p-ht500 --out_directory 4t-v20-syst
python aggregateSystematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet6to7-btag2-ht500 --out_directory 4t-v20-syst
python aggregateSystematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet6to7-btag1-ht500 --out_directory 4t-v20-syst
python aggregateSystematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet8p-btag3p-ht500 --out_directory 4t-v20-syst
python aggregateSystematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet8p-btag2-ht500 --out_directory 4t-v20-syst
python aggregateSystematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet8p-btag1-ht500 --out_directory 4t-v20-syst

