python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys LeptonSFDown 
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys LeptonSFUp
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys PUDown
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys PUUp
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys L1PrefireDown
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys L1PrefireUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys TriggerDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys TriggerUp
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFJesDown
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFJesUp
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFHfDown
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFHfUp
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFLfDown
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFLfUp
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFHfs1Down
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFHfs1Up
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFLfs1Down
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFLfs1Up
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFHfs2Down
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFHfs2Up
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFLfs2Down
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFLfs2Up
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFCfe1Down
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFCfe1Up
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFCfe2Down
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys BTagSFCfe2Up
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesTotalUp
python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesTotalDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesAbsoluteMPFBiasUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesAbsoluteMPFBiasDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesAbsoluteScaleUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesAbsoluteScaleDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesAbsoluteStatUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesAbsoluteStatDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeBalUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeBalDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeFSRUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeFSRDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeJEREC1Up
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeJEREC1Down
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeJEREC2Up
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeJEREC2Down
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeJERHFUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeJERHFDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativePtBBUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativePtBBDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativePtEC1Up
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativePtEC1Down
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativePtEC2Up
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativePtEC2Down
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativePtHFUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativePtHFDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeStatECUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeStatECDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeStatFSRUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeStatFSRDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeStatHFUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesRelativeStatHFDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpDataMCUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpDataMCDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpPtBBUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpPtBBDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpPtEC1Up
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpPtEC1Down
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpPtEC2Up
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpPtEC2Down
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpPtHFUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpPtHFDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpPtRefUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesPileUpPtRefDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesFlavorQCDUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesFlavorQCDDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesFragmentationUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesFragmentationDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesSinglePionECALUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesSinglePionECALDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesSinglePionHCALUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesSinglePionHCALDown
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesTimePtEtaUp
#python systematics.py --plot_directory 4t-v8.1-syst --selection trg-dilepL-minDLmass20-offZ1-njet8p-btag3-ht500 --sys jesTimePtEtaDown
