python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500  
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --wc cQQ1
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys LeptonSFDown  
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys LeptonSFUp 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PUDown 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PUUp 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys L1PrefireDown 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys L1PrefireUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys TriggerDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys TriggerUp 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFJesDown 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFJesUp 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFHfDown 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFHfUp 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFLfDown 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFLfUp 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFHfs1Down 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFHfs1Up 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFLfs1Down 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFLfs1Up 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFHfs2Down 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFHfs2Up 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFLfs2Down 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFLfs2Up 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFCfe1Down 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFCfe1Up 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFCfe2Down 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys BTagSFCfe2Up 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys noTopPtReweight
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys HDampUp 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys HDampDown 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys ScaleDownDown  
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys ScaleDownNone 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys ScaleNoneDown 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys ScaleNoneUp 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys ScaleUpNone 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys ScaleUpUp 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys ISRUp  
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys ISRDown 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys FSRUp 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys FSRDown 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_1  
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_2 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_3 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_4 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_5 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_6 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_7 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_8 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_9 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_10 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_11 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_12 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_13 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_14 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_15 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_16 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_17 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_18 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_19 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_20 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_21 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_22 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_23 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_24 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_25 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_26 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_27 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_28 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_29 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_30 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_31 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_32 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_33 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_34 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_35 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_36 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_37 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_38 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_39 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_40 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_41 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_42 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_43 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_44 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_45 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_46 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_47 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_48 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_49 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_50 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_51 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_52 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_53 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_54 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_55 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_56 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_57 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_58 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_59 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_60 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_61 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_62 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_63 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_64 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_65 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_66 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_67 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_68 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_69 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_70 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_71 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_72 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_73 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_74 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_75 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_76 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_77 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_78 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_79 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_80 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_81 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_82 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_83 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_84 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_85 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_86 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_87 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_88 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_89 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_90 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_91 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_92 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_93 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_94 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_95 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_96 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_97 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_98 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_99 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys PDF_100 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesTotalUp 
python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesTotalDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesAbsoluteMPFBiasUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesAbsoluteMPFBiasDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesAbsoluteScaleUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesAbsoluteScaleDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesAbsoluteStatUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesAbsoluteStatDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeBalUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeBalDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeFSRUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeFSRDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeJEREC1Up 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeJEREC1Down 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeJEREC2Up 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeJEREC2Down 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeJERHFUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeJERHFDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativePtBBUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativePtBBDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativePtEC1Up 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativePtEC1Down 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativePtEC2Up 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativePtEC2Down 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativePtHFUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativePtHFDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeStatECUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeStatECDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeStatFSRUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeStatFSRDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeStatHFUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesRelativeStatHFDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpDataMCUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpDataMCDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpPtBBUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpPtBBDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpPtEC1Up 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpPtEC1Down 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpPtEC2Up 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpPtEC2Down 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpPtHFUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpPtHFDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpPtRefUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesPileUpPtRefDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesFlavorQCDUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesFlavorQCDDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesFragmentationUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesFragmentationDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesSinglePionECALUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesSinglePionECALDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesSinglePionHCALUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesSinglePionHCALDown 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesTimePtEtaUp 
#python systematics.py --plot_directory 4t-v12-syst --selection trg-dilep-OS-minDLmass20-offZ1-lepVeto2-njet4p-btag2p-ht500 --sys jesTimePtEtaDown 
