copy_dir.py --source /scratch-cbe/users/maryam.shooshtari/tttt/nanoTuples/tttt_v8/UL2016/dilep/        --selection dilep-nlepFO2p-ht500 --target_subdir dilep-nlepFO2p-ht500 --target /scratch-cbe/users/$USER/tttt/nanoTuples/tttt_v8/UL2016 --cores 10
copy_dir.py --source /scratch-cbe/users/maryam.shooshtari/tttt/nanoTuples/tttt_v8/UL2016_preVFP/dilep/ --selection dilep-nlepFO2p-ht500 --target_subdir dilep-nlepFO2p-ht500 --target /scratch-cbe/users/$USER/tttt/nanoTuples/tttt_v8/UL2016_preVFP --cores 10
copy_dir.py --source /scratch-cbe/users/maryam.shooshtari/tttt/nanoTuples/tttt_v8/UL2017/dilep/        --selection dilep-nlepFO2p-ht500 --target_subdir dilep-nlepFO2p-ht500 --target /scratch-cbe/users/$USER/tttt/nanoTuples/tttt_v8/UL2017 --cores 10
copy_dir.py --source /scratch-cbe/users/maryam.shooshtari/tttt/nanoTuples/tttt_v8/UL2018/dilep/        --selection dilep-nlepFO2p-ht500 --target_subdir dilep-nlepFO2p-ht500 --target /scratch-cbe/users/$USER/tttt/nanoTuples/tttt_v8/UL2018 --cores 10

copy_dir.py --sampleSelection Run2 --source /scratch-cbe/users/maryam.shooshtari/tttt/nanoTuples/tttt_v7/UL2016/dilep/        --selection dilep-nlepFO2p-ht500 --target_subdir dilep-nlepFO2p-ht500 --target /scratch-cbe/users/$USER/tttt/nanoTuples/tttt_v8/UL2016 --cores 10
copy_dir.py --sampleSelection Run2 --source /scratch-cbe/users/maryam.shooshtari/tttt/nanoTuples/tttt_v7/UL2016_preVFP/dilep/ --selection dilep-nlepFO2p-ht500 --target_subdir dilep-nlepFO2p-ht500 --target /scratch-cbe/users/$USER/tttt/nanoTuples/tttt_v8/UL2016_preVFP --cores 10
copy_dir.py --sampleSelection Run2 --source /scratch-cbe/users/maryam.shooshtari/tttt/nanoTuples/tttt_v7/UL2017/dilep/        --selection dilep-nlepFO2p-ht500 --target_subdir dilep-nlepFO2p-ht500 --target /scratch-cbe/users/$USER/tttt/nanoTuples/tttt_v8/UL2017 --cores 10
copy_dir.py --sampleSelection Run2 --source /scratch-cbe/users/maryam.shooshtari/tttt/nanoTuples/tttt_v7/UL2018/dilep/        --selection dilep-nlepFO2p-ht500 --target_subdir dilep-nlepFO2p-ht500 --target /scratch-cbe/users/$USER/tttt/nanoTuples/tttt_v8/UL2018 --cores 10
