#python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample TTLep_pow_CP5  #SPLIT300
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample T_tch_pow   #SPLIT300
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample Tbar_tch_pow  #SPLIT100
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample T_tWch  #SPLIT100
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample TBar_tWch  #SPLIT100
#python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample TTTT  #SPLIT100
#python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample TTWToLNu #SPLIT50
#python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample TTWToQQ #SPLIT21
#python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample TTZToLLNuNu #SPLIT50
#python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample TTZToLLNuNu_m1to10 #SPLIT26
#python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample TTZToQQ #SPLIT50
#python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample TTHnobb #SPLIT50
#python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2017 --processingEra tttt_v4 --sample TTHTobb #SPLIT50
