python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample TTLep_pow_CP5  #SPLIT300
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample T_tch_pow   #SPLIT200
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample Tbar_tch_pow  #SPLIT100
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample T_tWch  #SPLIT56
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample TBar_tWch  #SPLIT90
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample TTTT  #SPLIT100
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample TTWToLNu #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample TTWToQQ #SPLIT10
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample TTZToLLNuNu #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample TTZToLLNuNu_m1to10 #SPLIT18
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample TTZToQQ #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample TTHnobb #SPLIT40
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016 --processingEra tttt_v4_btag_loose --sample TTHTobb #SPLIT50
