python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016 --processingEra tttt_v2 --sample TTLep_pow_CP5  #SPLIT300
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016 --processingEra tttt_v2 --sample TTTT  #SPLIT100
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016 --processingEra tttt_v2 --sample TTWToLNu #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016 --processingEra tttt_v2 --sample TTWToQQ #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016 --processingEra tttt_v2 --sample TTZToLLNuNu #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016 --processingEra tttt_v2 --sample TTZToLLNuNu_m1to10  #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016 --processingEra tttt_v2 --sample TTZToQQ #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016 --processingEra tttt_v2 --sample TTHnobb #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016 --processingEra tttt_v2 --sample TTHTobb #SPLIT50
