python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample TTLep_pow_CP5  #SPLIT212
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample T_tch_pow   #SPLIT200
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample Tbar_tch_pow  #SPLIT100
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample T_tWch  #SPLIT66
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample TBar_tWch  #SPLIT75
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample TTTT  #SPLIT100
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample TTWToLNu #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample TTWToQQ #SPLIT10
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample TTZToLLNuNu #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample TTZToLLNuNu_m1to10 #SPLIT18
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample TTZToQQ #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample TTHnobb #SPLIT40
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --btag_WP loose --skim dilep --era UL2016_preVFP --processingEra tttt_v5 --sample TTHTobb #SPLIT50
