python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016_preVFP --processingEra tttt_v2 --sample TTLep_pow_CP5  #SPLIT212
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016_preVFP --processingEra tttt_v2 --sample TTTT  #SPLIT100
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016_preVFP --processingEra tttt_v2 --sample TTWToLNu #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016_preVFP --processingEra tttt_v2 --sample TTWToQQ #SPLIT10
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016_preVFP --processingEra tttt_v2 --sample TTZToLLNuNu #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016_preVFP --processingEra tttt_v2 --sample TTZToLLNuNu_m1to10 #SPLIT18
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016_preVFP --processingEra tttt_v2 --sample TTZToQQ #SPLIT50
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016_preVFP --processingEra tttt_v2 --sample TTHnobb #SPLIT40
python nanoPostProcessing.py  --overwrite --forceProxy --addDoubleB --skim dilep --era UL2016_preVFP --processingEra tttt_v2 --sample TTHTobb #SPLIT50
